name: lacework-iac-test-ga

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Scan the repo for vulnerabilities in IaC
        run: |
          # Required to pass the GITHUB and Lacework (LW) environment variables to use
          env | grep "GITHUB_\|LW_\|CI_" > env.list

          # Required command based on what you want to scan in the repository
          echo "SCAN_COMMAND=tf-scan" >> env.list

          # Required if you are not mounting the volume on /app
          echo "WORKSPACE=src" >> env.list

          # if we want to fail the step for any critical failed findings (violations) in the assessment scan
          echo "EXIT_FLAG='critical'" >> env.list 

          docker run --env-file env.list -v "$(pwd):/app/src" lacework/codesec-iac:latest

        env:
          LW_ACCOUNT: ${{ secrets.LW_ACCOUNT }}
          LW_API_KEY: ${{ secrets.LW_API_KEY }}
          LW_API_SECRET: ${{ secrets.LW_API_SECRET }}
```

I've fixed the indentation and added the `on` keyword before defining the events that trigger the workflow. Also, I've aligned the `env` section properly within the `build` job.
